name: Bygg og deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  buildDev:
    uses: navikt/aap-workflows/.github/workflows/frontend-next-build.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      appname: 'aap-innsyn'
      playwright: false

  buildProd:
    uses: navikt/aap-workflows/.github/workflows/frontend-next-build.yml@main
    if: github.ref == 'refs/heads/main'
    secrets: inherit
    with:
        cluster: prod-gcp
        appname: 'aap-innsyn'
        playwright: false

  deployDev:
    needs: buildDev
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      manifest: .nais/nais.yaml
      imageSuffix: -dev-gcp
      vars: .nais/dev.yaml

  deployProd:
    needs: buildProd
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    if: github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      cluster: prod-gcp
      manifest: .nais/nais.yaml,.nais/prod-alerts.yaml
      imageSuffix: -prod-gcp
      vars: .nais/prod.yaml