name: Bygg og deploy test

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#    types: [ closed ]

jobs:
  buildDev:
    uses: navikt/aap-workflows/.github/workflows/frontend-next-build.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      appname: 'aap-innsyn'
      playwright: false

  deployDev:
    needs: buildDev
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      manifest: .nais/nais.yaml
      imageSuffix: -dev-gcp
      vars: .nais/dev.yaml